### PR TITLE
You can't have a key without a value in JSON

### PR DESCRIPTION
**Pull request by cryos**
## Description
To the best of my knowledge at least, it is not possible to have a key
without a value, and it also seems like it would be simpler to check for
a known key, and then look at the value as a version, etc.

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dgasmith** [comment]
Currently isn't this just the first part of a list of someone wishes to stream the JSON in? Should be fine I think.

**Comment by cryos** [comment]
Looking at the JSON spec it just didn't look like that was possible, JSON is built on two structures - a collection of name/value pairs and an ordered list of values. I will see if I can create a key with no corresponding value in the libraries we use, but to the best of my knowledge that wasn't possible, and reading https://www.json.org/ it doesn't seem to be listed as a possibility.

**Comment by dgasmith** [comment]
Hmm, I might be confused. Isn't the base structure a list rather than a dict?

AFAIK we were originally split if you could start a JSON structure with a list or not. The parsers I have tried seem to accept it without issue.

**Comment by cryos** [comment]
So in my testing the JSON module in Python was OK with it, but the jsoncpp library we use in Avogadro 2 complained about a missing ':' after object member name, and when I attempted to write out an empty key assigned it a value of null. I wonder how many JSON parsers will support it out of the box. The parser just failed to parse the file, so I couldn't continue loading it without making a change to the JSON.

**Comment by cryos** [comment]
Ah, that might be where I was confused actually, I think I get you now. Let me try that, I think you are right, and I was looking at this wrong - not used to starting as a list but that does seem to be supported just fine.

**Comment by cryos** [comment]
Sorry for the noise, apparently slow getting my brain back into the JSON world....

**Pull request closed without merging**
